Repository Cairo-Squad/EvolveFit, pull requests merged in 2025-08, with the labels that each got.

#42 Create OnBoarding Header component
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/onBoarding/OnboardingHeader.kt
Labels: component

#69 feature/nutrition-screen
  composeApp/src/commonMain/composeResources/values-ar/strings.xml
  composeApp/src/commonMain/composeResources/values/strings.xml
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/design_system/component/CircularPercentageIndicator.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/design_system/component/InputField.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/design_system/component/SnackBar.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/di/viewModelModule.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/nutrition/NutritionScreen.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/nutrition/content/MealHistoryItem.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/nutrition/content/MealTypeDropdown.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/nutrition/content/NutritionSummaryCard.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/nutrition/content/SuggestedMeals.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/nutrition/content/TodayMeals.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/nutrition/NutritionEffect.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/nutrition/NutritionInteractionListener.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/nutrition/NutritionScreenState.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/nutrition/NutritionViewModel.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/nutrition/mappers.kt
Labels: screen, feature

#102 refactor: split the entities to multiple files.
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/entity/Exercise.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/entity/FitnessGoal.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/entity/FocusArea.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/entity/Gender.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/entity/MeasurementType.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/entity/MeasurementUnit.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/entity/Tool.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/entity/User.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/entity/WorkoutDay.kt
Labels: enhancement

#119 Feature/edit profile
  composeApp/src/commonMain/composeResources/drawable/ic_pen.svg
  composeApp/src/commonMain/composeResources/values-ar/strings.xml
  composeApp/src/commonMain/composeResources/values/strings.xml
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/design_system/component/BottomSheet.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/design_system/component/InputField.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/design_system/component/LabeledInputField.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/di/repositoryModule.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/di/useCaseModule.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/di/viewModelModule.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/domain/repository/EquipmentRepository.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/domain/repository/ProfileRepository.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/domain/usecase/equipment/ManageEquipmentUseCase.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/domain/usecase/profile/ManageProfileUseCase.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/repository/equipment/EquipmentRepositoryImpl.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/repository/profile/ProfileRepositoryImpl.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/component/DateBottomSheet.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/component/UiImageDisplayer.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/component/UserProfileImage.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/navigation/NavigationHost.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/navigation/Routes.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/app/AppScreen.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/editProfile/EditProfileScreen.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/editProfile/content/GenderBottomSheet.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/editProfile/content/HeightBottomSheet.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/editProfile/content/MainGoalBottomSheet.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/editProfile/content/MeasurementUnitBottomSheet.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/editProfile/content/ToolsBottomSheet.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/editProfile/content/WeightBottomSheet.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/editProfile/content/WorkOutDaysBottomSheet.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/more/MoreScreen.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/register/content/RegisterHeader.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/register/content/RegisterScreenContentSelectHeightAndWeight.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/editProfile/EditProfileEffect.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/editProfile/EditProfileInteractionListener.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/editProfile/EditProfileScreenState.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/editProfile/EditProfileViewModel.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/editProfile/mapper.kt
Labels: feature

#180 Refactor/home screen state
  composeApp/src/commonMain/composeResources/values-ar/strings.xml
  composeApp/src/commonMain/composeResources/values/strings.xml
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/domain/usecase/home/GetPersonalizedWorkoutsUseCase.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/home/HomeLoadingScreen.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/home/HomeScreen.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/home/HomeInteractionListener.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/home/HomeScreenState.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/home/HomeViewModel.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/nutrition/NutritionViewModel.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/utils/handleUiErrors.kt
Labels: enhancement, feature

#183 Refactor/shimmer loading favourite meal
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/favorites/FavoritesLoadingScreen.kt
Labels: enhancement, feature

#219 Fix/nutrition issues
  composeApp/src/commonMain/composeResources/values-ar/strings.xml
  composeApp/src/commonMain/composeResources/values/strings.xml
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/domain/exception/AppException.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/domain/model/FieldType.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/domain/model/MealType.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/domain/usecase/nutrition/ManageNutritionUseCase.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/domain/usecase/utils/Extentions.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/domain/usecase/utils/Validation.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/nutrition/NutritionScreen.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/nutrition/component/MealHistoryItem.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/nutrition/component/MealTypeDropdown.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/suggested_meals/SuggestedMealsScreen.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/meal_details/mappers.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/meal_history/mappers.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/nutrition/NutritionInteractionListener.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/nutrition/NutritionScreenState.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/nutrition/NutritionViewModel.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/nutrition/mappers.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/suggested_meals/mappers.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/utils/handleUiErrors.kt
Labels: bug

#304 Feature/handle loading meal history
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/mealsHistory/MealsHistoryScreen.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/mealsHistory/content/components/MealHistoryErrorScreen.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/mealsHistory/content/components/MealHistoryLoadingScreen.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/mealsHistory/content/components/MealsHistorySuccessScreen.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/meal_history/MealHistoryInteractionListener.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/meal_history/MealHistoryScreenState.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/meal_history/MealHistoryViewModel.kt
Labels: bug

#309 Fix/nutrition issuess
  composeApp/src/commonMain/composeResources/values-ar/strings.xml
  composeApp/src/commonMain/composeResources/values/strings.xml
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/design_system/component/InputField.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/domain/usecase/nutrition/ManageNutritionUseCase.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/nutrition/component/MealTypeDropdown.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/nutrition/content/SeeAll.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/nutrition/content/TodayMeals.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/nutrition/NutritionScreenState.kt
  composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/nutrition/NutritionViewModel.kt
Labels: bug
